### ISSUE TITLE
上传二三十兆的文件会报错，必现，请问有什么解决办法吗

### ISSUE THREAD

**Issue by Clearlee** [lizhangqu/CoreProgress#11]
log如下：
08-16 16:40:52.986 4527-4527/io.github.lizhangqu.sample E/TAG: onUIProgressStart:25930457
08-16 16:40:53.002 4527-4527/io.github.lizhangqu.sample D/TAG: =============start===============
08-16 16:40:53.003 4527-4527/io.github.lizhangqu.sample D/TAG: numBytes:8192
08-16 16:40:53.004 4527-4527/io.github.lizhangqu.sample D/TAG: totalBytes:25930457
08-16 16:40:53.004 4527-4527/io.github.lizhangqu.sample D/TAG: percent:3.1592193E-4
08-16 16:40:53.004 4527-4527/io.github.lizhangqu.sample D/TAG: speed:0.0
08-16 16:40:53.005 4527-4527/io.github.lizhangqu.sample D/TAG: ============= end ===============
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: =============start===============
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: numBytes:491520
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: totalBytes:25930457
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: percent:0.018955316
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: speed:4603.0
08-16 16:40:53.028 4527-4527/io.github.lizhangqu.sample D/TAG: ============= end ===============
08-16 16:40:53.126 4527-4527/io.github.lizhangqu.sample D/TAG: =============start===============
08-16 16:40:53.126 4527-4527/io.github.lizhangqu.sample D/TAG: numBytes:1458176
08-16 16:40:53.126 4527-4527/io.github.lizhangqu.sample D/TAG: totalBytes:25930457
08-16 16:40:53.126 4527-4527/io.github.lizhangqu.sample D/TAG: percent:0.056234106
08-16 16:40:53.126 4527-4527/io.github.lizhangqu.sample D/TAG: speed:8479.0
08-16 16:40:53.127 4527-4527/io.github.lizhangqu.sample D/TAG: ============= end ===============
08-16 16:40:54.008 4527-5008/io.github.lizhangqu.sample D/TAG: =============onFailure===============
08-16 16:40:54.020 4527-5008/io.github.lizhangqu.sample E/TAG: java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                   at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
                                                                   at libcore.io.IoBridge.sendto(IoBridge.java:511)
                                                                   at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
                                                                   at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
                                                                   at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                                                                   at okio.Okio$1.write(Okio.java:79)
                                                                   at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
                                                                   at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                   at okio.RealBufferedSink.write(RealBufferedSink.java:41)
                                                                   at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
                                                                   at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                   at okio.RealBufferedSink$1.write(RealBufferedSink.java:193)
                                                                   at io.github.lizhangqu.coreprogress.ProgressOutputStream.write(ProgressOutputStream.java:39)
                                                                   at okio.Okio$1.write(Okio.java:79)
                                                                   at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                   at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
                                                                   at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
                                                                   at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                                                                   at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                                                                   at io.github.lizhangqu.coreprogress.ProgressRequestBody.writeTo(ProgressRequestBody.java:54)

**Comment by lizhangqu** [comment]
see [https://github.com/square/okhttp/issues/1775](https://github.com/square/okhttp/issues/1775)

and [https://stackoverflow.com/questions/14622700/android-socket-java-net-socketexception-sendto-failed-epipe-broken-pipe](https://stackoverflow.com/questions/14622700/android-socket-java-net-socketexception-sendto-failed-epipe-broken-pipe)

**Comment by Clearlee** [comment]
谢谢，不过你提供的链接我都有搜索到，但是没有找到明确的解决办法，很奇怪的是，如果我不监听文件的上传进度，文件是可以正常上传的，使用你的方法监听进度的时候就会有问题，所以想请教下你有没有什么解决办法。。。

**Comment by Clearlee** [comment]
解决了，是因为服务器限制了单次上传文件大小导致的问题，放开限制就好了。
